### ISSUE TITLE
Build Lang: RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by galaxyoyo** [lsmoura/mtgjson#130]
Hello

I tried to build lang data for C15 with running `node buildLang.js C15 fr` under Windows, but I got this error :

>RangeError: Maximum call stack size exceeded
    at next (C:\MTG\MTGJSON\node_modules\tiptoe\index.js:48:22)
    at CBIterator.next [as cb] (C:\MTG\MTGJSON\node_modules\tiptoe\index.js:53:4)
    at CBIterator.CBIterator.finish (C:\MTG\MTGJSON\node_modules\xbase\Array.js:960:16)
    at CBRunner.<anonymous> (C:\MTG\MTGJSON\node_modules\xbase\Array.js:913:51)
    at CBRunner.fun (C:\MTG\MTGJSON\build\buildLang.js:127:6)
    at CBRunner.CBRunner.run (C:\MTG\MTGJSON\node_modules\xbase\Array.js:913:8)
    at CBIterator.CBIterator.next (C:\MTG\MTGJSON\node_modules\xbase\Array.js:947:18)
    at CBIterator.CBIterator.finish (C:\MTG\MTGJSON\node_modules\xbase\Array.js:962:8)
    at CBRunner.<anonymous> (C:\MTG\MTGJSON\node_modules\xbase\Array.js:913:51)
    at CBRunner.fun (C:\MTG\MTGJSON\build\buildLang.js:127:6)

Any idea to fix this ?

EDIT : Ok,  I found quickly, just needed to replace `gc();` by `setImmediate(gc);` I make a pull request now.

**Comment by galaxyoyo** [comment]
Fixed in #131
