### ISSUE TITLE
mhash install error on OSX

### ISSUE THREAD

**Issue by carlol** [lsmoura/mtgjson#165]
Hi, I'm trying to run the buildSet.js script but I recognized an error during the node_module installation:

```
../mhash.cc:129:34: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
Handle<Value> hash_binding(const Arguments& args)
                                 ^~~~~~~~~
                                 v8::internal::Arguments
/Users/carloluchessa/.node-gyp/4.4.4/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../mhash.cc:131:15: error: calling a protected constructor of class 'v8::HandleScope'
        HandleScope     scope;
                        ^
/Users/carloluchessa/.node-gyp/4.4.4/include/node/v8.h:885:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../mhash.cc:136:30: error: type 'const v8::internal::Arguments' does not provide a subscript operator
        String::Utf8Value       name(args[0]->ToString());
                                     ~~~~^~
../mhash.cc:139:10: error: no matching function for call to 'Null'
                return Null();
                       ^~~~
/Users/carloluchessa/.node-gyp/4.4.4/include/node/v8.h:8130:18: note: candidate function not viable: requires single argument 'isolate', but no arguments were provided
Local<Primitive> Null(Isolate* isolate) {
                 ^
../mhash.cc:141:9: error: type 'const v8::internal::Arguments' does not provide a subscript operator
        if(args[1]->IsString())
           ~~~~^~
../mhash.cc:143:31: error: type 'const v8::internal::Arguments' does not provide a subscript operator
                String::Utf8Value       data(args[1]->ToString());
                                             ~~~~^~
../mhash.cc:146:34: error: type 'const v8::internal::Arguments' does not provide a subscript operator
        else if(Buffer::HasInstance(args[1]))
                                    ~~~~^~
../mhash.cc:148:29: error: type 'const v8::internal::Arguments' does not provide a subscript operator
                Handle<Object> data = args[1]->ToObject();
                                      ~~~~^~
../mhash.cc:153:10: error: no matching function for call to 'Null'
                return Null();
                       ^~~~
/Users/carloluchessa/.node-gyp/4.4.4/include/node/v8.h:8130:18: note: candidate function not viable: requires single argument 'isolate', but no arguments were provided
Local<Primitive> Null(Isolate* isolate) {
                 ^
../mhash.cc:155:16: error: no member named 'New' in 'v8::String'
        ret = String::New(hashed);
              ~~~~~~~~^
../mhash.cc:158:15: error: no member named 'Close' in 'v8::HandleScope'
        return scope.Close(ret);
               ~~~~~ ^
../mhash.cc:163:15: error: calling a protected constructor of class 'v8::HandleScope'
        HandleScope             scope;
                                ^
/Users/carloluchessa/.node-gyp/4.4.4/include/node/v8.h:885:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../mhash.cc:165:22: error: no member named 'New' in 'v8::String'
        target->Set(String::New("hash"), FunctionTemplate::New(hash_binding)->GetFunction());
                    ~~~~~~~~^
../mhash.cc:165:57: error: cannot initialize a parameter of type 'v8::Isolate *' with an lvalue of type 'Handle<v8::Value> (const v8::internal::Arguments &)'
        target->Set(String::New("hash"), FunctionTemplate::New(hash_binding)->GetFunction());
                                                               ^~~~~~~~~~~~
/Users/carloluchessa/.node-gyp/4.4.4/include/node/v8.h:4350:16: note: passing argument to parameter 'isolate' here
      Isolate* isolate, FunctionCallback callback = 0,
               ^
14 errors generated.
make: *** [Release/obj.target/mhash/mhash.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/carloluchessa/.nvm/versions/node/v4.4.4/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/Users/carloluchessa/.nvm/versions/node/v4.4.4/bin/node" "/Users/carloluchessa/.nvm/versions/node/v4.4.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/carloluchessa/Personal/MTGU/mtgu_card_extractor/mtgjson/node_modules/mhash
gyp ERR! node -v v4.4.4
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
```

I used nodejs a bit some years ago but I am not an expert for sure.
I try to run npm install using node 0.10.0 and 4.4.4 versions.

**Comment by lsmoura** [comment]
It's an error on mhash package. You can either wait for the pull request https://github.com/Sembiance/mhash/pull/19 be finalized or use the https://github.com/mtgjson/mhash.git repository instead (temporarily).
